### ISSUE TITLE
Move adccore to adcc

### ISSUE THREAD

**Issue by maxscheurer** [adc-connect/adcc#105]
Just an issue to keep track of things that need to be done:

- [x] merge #71 
- [x] merge #104 
- [x] Deploy libtensor to github release (for MacOS and Linux)
- [x] Deploy libtensor to conda (WIP already)
- [x] Merge codes
- [x] Restructure repo
- [x] Update deployment infrastructure
- [x] transfer issues from core repository

**Comment by mfherbst** [comment]
Good idea. Just edited your comment.

**Comment by maxscheurer** [comment]
Are you already working on moving adccore files to adcc? Just want to make sure we don't work both on the same task.

**Comment by mfherbst** [comment]
Yes. I'm on it.
