### ISSUE TITLE
Conda dev deployment

### ISSUE THREAD

**Issue by mfherbst** [adc-connect/adcc#115]
Is it really necessary to deploy all four python versions and all two OSes to Conda for each push to master? I would suggest it is more economical to stick only to the two latest python versions and maybe even drop macOS? What do you think @maxscheurer?

**Comment by maxscheurer** [comment]
I think if we want to maintain full compatibility with Psi4, we should deploy all versions...

**Comment by maxscheurer** [comment]
Sorry, I did not read this well enough 😄 
`dev` deployments should be limited to Linux and a single Python version IMHO.
Deployments to `main` should be all 4 versions on macOS and Linux.

**Comment by mfherbst** [comment]
All right to that I can 100% agree. Because that's not what happens right now :smile:.

**Comment by maxscheurer** [comment]
I don't know... deployments to `dev` are using py38 only right now?! So if the label is set correctly, only py38 should be deployed to `dev` for Linux & macOS (with the current configuration).

**Comment by mfherbst** [comment]
Ah yes you might be right. Might have been my mistake. Ok let's see. I let the CI run through on master. Sorry.

**Comment by maxscheurer** [comment]
It's not a problem, hope everything works as expected now.
The best thing is that we succeeded to deploy ALL versions to conda main now, that's pretty amazing! Less than 1 hour for all 4 py versions on each platform 💪

**Comment by mfherbst** [comment]
Plus pip ... if you compare to the pain we had before ...

**Comment by mfherbst** [comment]
Everything seems to work as expected (only 3.8 deployed).
