### ISSUE TITLE
Use GHA Setup-Miniconda

### ISSUE THREAD

**Issue by maxscheurer** [adc-connect/adcc#120]
Maybe it would be easier (less code to maintain) to use [setup-miniconda](https://github.com/marketplace/actions/setup-miniconda) instead of our self-made approach.

**Comment by mfherbst** [comment]
Honestly ... you're the conda guy. If you think that will make things easier, go for it!

**Comment by maxscheurer** [comment]
Yes... probably at some point, just wanted to leave this as a note here so I don't forget it exists. 😬
