### ISSUE TITLE
Conda-forge deployment

### ISSUE THREAD

**Issue by maxscheurer** [adc-connect/adcc#138]
I'd like to test deployment of libtensorlight/adcc via conda-forge. Comments etc. can be added to this issue 😄 

- [x] deploy libtensorlight
- [x] deploy adcc
- [x] adapt documentation and badges
- [x] nuke conda deployment from repo

**Comment by maxscheurer** [comment]
`libtensorlight` already up on c-f ✅

**Comment by mfherbst** [comment]
Very nice. Let me know if you need to discuss something. I know some people from the conda-forge team I could summon.

**Comment by maxscheurer** [comment]
I had some problems yesterday but everything is running smoothly now I guess: https://github.com/conda-forge/staged-recipes/pull/17477

**Comment by maxscheurer** [comment]
BTW I can add you as package maintainer if you want 😬

**Comment by mfherbst** [comment]
I don't have strong feelings about it, but why not?

**Comment by mfherbst** [comment]
Why did you disable the sha256sum check by the way. I'm not sure this is a good idea.

**Comment by maxscheurer** [comment]
The sha256sum on c-f VM does not support the `--ignore-missing` option. Maybe you have a suggestion how one could patch the script instead? 😬

**Comment by mfherbst** [comment]
I guess what you could do is "preprocess" the SHA256SUM file to only contain the files which are truely there, e.g. something like
```bash
while read line; do
     [ -f "$line" ] && echo "$line" >> SHA256SUM.filtered
done < SHA256SUM
```

**Comment by maxscheurer** [comment]
I'm keeping track of the next steps here (in order):

- [ ] merge #141 
- [ ] remove own conda pipeline
- [ ] release `v0.15.10`
- [ ] upload new docs (currently online is `v0.15.7` (@mfherbst)
- [ ] adapt recipe on c-f for `v0.15.10` (remove patch & dependencies) (@maxscheurer)
- [ ] adapt documentation and badges once `adcc` is on c-f

**Comment by mfherbst** [comment]
> upload new docs (currently online is v0.15.7)

Seriously ... that's my bad.

**Comment by maxscheurer** [comment]
We should probably somehow discontinue the `adcc` channel on anaconda.org. I don't know if we should leave it up there for some "grace period"? Opinions, @mfherbst and @loriab (if you need the current adcc channel versions)?

**Comment by mfherbst** [comment]
Agree, we should leave it up for some time. Perhaps we could push a last version by a manual build (?), which includes a warning upon import?

**Comment by maxscheurer** [comment]
That's a good suggestion! Can do the manual build for `0.15.11` and upload it to the adcc channel. I would say we remove our own channel once 0.16.0 comes out.

**Comment by mfherbst** [comment]
Sounds fair. That'll probably be the case when another major feature (LR-PCM ?) goes in.

**Comment by maxscheurer** [comment]
Yes, PCM (#132) and gradients (#124) should be in `0.16.0`.

**Comment by maxscheurer** [comment]
@mfherbst if you find the time, could you push the `v0.15.13` docs to the website?

**Comment by mfherbst** [comment]
Done.
