### ISSUE TITLE
How to change the location of scratch directory

### ISSUE THREAD

**Issue by ggdhzdx** [adc-connect/adcc#150]
My 500GB /tmp directory is not large enough for ADC2 calculation and  "No space left on device" erros raises as below:
```
[Errno 28] Can't write data (file write failed: time = Wed Mar 16 14:37:59 2022
, filename = '/tmp/tmpz2zekel8', file descriptor = 6, errno = 28, error message = 'No space left on device', buf = 0x151316c52c90, total write size = 83890048, bytes this sub-write = 83890048, bytes actually written = 18446744073709551615, offset = 0)

```
I search the docs for methods to change the location of scratch dir but failed

**Comment by maxscheurer** [comment]
Are you using adcc in combination with pyscf? This looks to me like the pyscf scratch file/directory. BTW if you don't use the libxm allocator in adcc, adcc itself won't write anything to disk, it keeps everything in RAM.

**Comment by ggdhzdx** [comment]
Yes, problem solved! It's a pyscf scrach directory. Thanks a lot
