### ISSUE TITLE
Future of reference data for tests

### ISSUE THREAD

**Issue by maxscheurer** [adc-connect/adcc#159]
In #158, a fix for erroneous working equations (transition densities) is implemented, such that the ADC reference data for the related properties (generated from `pyadcman` are no longer valid. The question is how one should deal with such a case, because so far we did not have any similar case during the development of `adcc`. I think it would be super tedious to include the fix inside `pyadcman` (and the underlying libraries) just to get such a PR in. 

From my point of view, it would be best to re-generate the reference data with `adcc` (i.e. create additional ref files), test everything we know is "correct" in `pyadcman` using the "legacy" reference data, plus expand the consistency/functionality tests using the `adcc`-generated data.

@apapapostolou thanks for bringing this up. I think since you are mostly affected by this and we discussed it already, do you agree that this "dual-test" mode above is reasonable?

**Comment by mfherbst** [comment]
> I think it would be super tedious to include the fix inside pyadcman (and the underlying libraries) just to get such a PR in.

We did this in the past, but I guess one could argue that adcc starts to have a solid standing by itself and pyadcman might have outlived itself. I mean is anyone even actively using or maintaining it? As far as I remember it is basically built upon the old adccore infrastructure, which might just stop working at some point.

So with that said, I'm fully on board with your suggestion. To avoid duplicate efforts we could also just patch the data coming from pyadcman directly and in this way essentially decouple the generator from the data. Or do you think that could be too confusing?

**Comment by maxscheurer** [comment]
I think it's a bit too confusing, because the "provenance" of the reference data would be at least to some extent unclear.
I suggest to keep some `test_functionality_legacy.py` (or similar) which uses the `pyadcman` reference data (excitation energies, etc., things we are 99.999999% sure are correct). The reference data generated by `adcc` itself could then serve as consistency tests, where one has to re-generate if anything severe changes.

In my opinion, this could be the clearest and least invasive strategy. @apapapostolou what do you think?

**Comment by apapapostolou** [comment]
I agree with you, @maxscheurer. Even though it’s a bit of work, it’s probably best to regenerate all the reference data with `adcc` and then use that for consistency testing. I would still keep the `pyadcman` reference data and use it for tests that don't involve properties (or just electric ones without CVS). However, I don't think I would start mixing reference data.

I think this is the easiest way for future users to trace the origin of the reference data.

**Comment by mfherbst** [comment]
Sounds good. I'm onboard.

**Comment by maxscheurer** [comment]
Closed in #158.
