### ISSUE TITLE
Binder is broken

### ISSUE THREAD

**Issue by maxscheurer** [adc-connect/adcc#46]
Some `openblas` version mismatch currently prohibits usage of Binder. Probably we can pin an older version in the Binder environment file.

**Comment by mfherbst** [comment]
I'm not sure it's that simple, actually, because openblas 0.something actually gets installed, so it should get found as well.

I tried experimenting with adcc from conda, but no luck so far. Do you have any clue, to which version we should downgrade?

**Comment by mfherbst** [comment]
Using dev channels for adcc and psi4 works ...
