### ISSUE TITLE
User-defined property_method

### ISSUE THREAD

**Issue by maxscheurer** [adc-connect/adcc#58]
Is there currently a canonical way to provide the `property_method` to the `ExcitedStates` object and/or `run_adc` itself? I couln't find anything, except for re-creating the `ExcitedStates` object that drops out like ```state2 = ExcitedStates(state, property_method="adc0")``` should do the job.

**Edit**: The above solution requires small changes in the `ExcitedStates` class, such that
the property `excitation_energies`/`excitation_vectors` of `data` are copied.

Motivation would be to run a "real" CIS calculation (ADC(1)/ISR(0)) to compare rotatory strengths with PySCF/Dalton etc.

**Comment by mfherbst** [comment]
Not really. Especially I would consider such stuff "advanced usage" and thus for me is not really part of the scope of a "normal" `run_adc`, so I definitely vote against adding this to `run_adc`.

But in this case I think you raise a pretty interesting point. Maybe we should actually make the `property_method` property settable? If you set it you have to discard the cached values, but that sounds fair to me. Also solves the question of making it easy to use other potential combinations of adc / property calculation.

In either way: Would you mind adding a two-liner `adcc.cis` method in the spirit of the `adcN` methods just calling `run_adc` and setting the property level to isr(0) before returning the `state`. That sounds quite useful to me. Thanks!

**Comment by maxscheurer** [comment]
> Would you mind adding a two-liner adcc.cis

This is what I had in mind as well 👍 Will be done in #56 

> Maybe we should actually make the property_method property settable

Yes, let's make an extra PR for this.

**Comment by maxscheurer** [comment]
I guess the property method can (now) be passed to the ctor of `ExcitedStates`. I'd avoid having a settable property method, because you can just copy-construct a new instance of `ExcitedStates` from the old one with a specified property method.
