### ISSUE TITLE
Tests broken because of issues with PySCF/CPPE

### ISSUE THREAD

**Issue by mfherbst** [adc-connect/adcc#72]
@maxscheurer Tests are currently broken because of issues with integration with CPPE. Could you have a look?

Travis example: https://travis-ci.org/github/adc-connect/adcc/jobs/695614235#L4316

**Comment by maxscheurer** [comment]
It's actually not a `cppe` problem per se, but a `pyscf` one 😄 I updated the option interface in `cppe`, the PR for `pyscf` was merged yesterday night, so when the next `pyscf` release comes to `pip`, everything should work fine again.

**Comment by maxscheurer** [comment]
Quick update: once the `pyscf` on `pip` supports the newest `cppe` version, we can just do `pip install cppe` in our Travis config.

**Comment by mfherbst** [comment]
Cool :+1:. Just make a PR and we can close this.
